title: "Carolina Rios Trujillo"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
avatar: assets/images/WhatsApp Image 2025-01-17 at 12.56.13 PM.jpeg
include: ["assets/css/custom-style.css"]
