title: "Carolina Rios Trujillo"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
avatar: assets/images/WhatsApp Image 2025-01-21 at 10.29.28 AM.jpeg
include: ["assets/css/custom-style.css"]
google_site_verification: "google6a939adc49c6fc66.html" #PLEASE DO NOT USE THIS CODE ON YOUR OWN REPO! 
github:
  is_project_page: false
